DROP TRIGGER IF EXISTS TOTEHDR_U;
DELIMITER //
CREATE TRIGGER TOTEHDR_U
BEFORE UPDATE ON TOTEHDR FOR EACH ROW
BEGIN
    IF (OLD.tote_type = "RET") THEN 
     set NEW.tote_type = OLD.tote_type;
    END IF;
END//
DELIMITER ;
